version: '3.3'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 8090:8090
    depends_on:
      - mongo
      - redis
    volumes:
      - ./src:/i-relay/src
      - ./swagger.json:/i-relay/swagger.json
      - ./.env.local:/i-relay/.env
      - ./node_modules:/i-relay/node_modules
    networks:
      - i-relay
  redis:
    build:
      context: .
      dockerfile: Dockerfile.redis
    ports:
      - 6379:6379
    networks:
      - i-relay
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27018:27017
    depends_on:
      - redis
    networks:
      - i-relay
networks:
  i-relay:
    driver: bridge